FROM python:3.12-bookworm

WORKDIR /app

COPY ./requirements.txt /requirements.txt
RUN pip install --no-cache-dir --upgrade -r /requirements.txt

RUN apt-get update && apt-get install -y p7zip

COPY src/ .

